sudo: false

addons:
 apt:
   packages:
     - graphviz

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

language: scala

jdk:
  - oraclejdk8

script:
  # - sbt "set parallelExecution in Global := false" +test
  - sbt clean coverage "set parallelExecution in Global := false" +test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0270f9f1bd0fccba09a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    condition: -e ./deploy.sh
    all_branches: true
